# Site wide configuration

title: 泃河湾当家的玩耍的地方
description:
logo:  # 120x120 px default image used for Twitter summary card
teaser: tesar01.png # 400x250 px default teaser image used in image archive grid
locale:
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


image:
  path: image/

# Site owner
owner:
  name: i9527
  email: juhetuf@163.com
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: author_01.jpg # 160x160 px image for author byline
  disqus-shortname: i9527


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
